// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIyUbQitpmfFPwOXujC2oHS0NAU1XJjGs',
    appId: '1:704173359839:web:5a5c0ad1519ef800fb5f6a',
    messagingSenderId: '704173359839',
    projectId: 'ride-hailing-app-68e81',
    authDomain: 'ride-hailing-app-68e81.firebaseapp.com',
    storageBucket: 'ride-hailing-app-68e81.appspot.com',
    measurementId: 'G-50Q1H0L38G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCktX1ob4acTROgV1-hdSgXiSwZwREe3X4',
    appId: '1:704173359839:android:3e5ccd283b01670dfb5f6a',
    messagingSenderId: '704173359839',
    projectId: 'ride-hailing-app-68e81',
    storageBucket: 'ride-hailing-app-68e81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGyuzjgNByyFEj0T0AEMxo74ssgSJdpYc',
    appId: '1:704173359839:ios:7f34987c9694d48afb5f6a',
    messagingSenderId: '704173359839',
    projectId: 'ride-hailing-app-68e81',
    storageBucket: 'ride-hailing-app-68e81.appspot.com',
    iosBundleId: 'com.example.pakyaw',
  );
}
